### ISSUE TITLE
configurable line-spacing in crengine

### ISSUE THREAD

**Issue by dpavlin** [koreader/kindlepdfviewer#102]
I did a quick grep over crengine source code, and it seems that they are modifing CSS values to get configurable line space (I'm basing this assumption on code from `crengine/crengine/src/lvtinydom.cpp`.

We should probably have to do something similar, since Linux Journal epubs seem to have too little line spacing to be comfortable read...

I don't have a clear idea where to start, but hopefully @houqp does :-)

**Comment by houqp** [comment]
Following your guidance, I also took a look at lvtinydom and I found two interesting methods in **_lxmlDocBase**_ class:

``` c++
inline LVStyleSheet * getStyleSheet() { return &_stylesheet; }
/// sets style sheet, clears old content of css if arg replace is true
void setStyleSheet( const char * css, bool replace );
```

**_lxmlDocBase**_ is the base class of **_ldomDocument**_ and In `cre.cpp`, we stores a pointer to a **_ldomDocument**_ instance in CreDocument structure on document open. So I suspect these two methods might be usefull for adjusting line height.

Or we can use the `getStyle()` and `setStyle()` method from **_ldomNode**_ class. **_ldomDocument**_ class has a `getRootNode()` method that returns the root node of opened document.

UPDATE: The latter approach might be easier because it uses `css_style_rec_tag` structure, which has a member named `line_height`. So maybe we can just update this value.

**Comment by hwhw** [comment]
I took the freedom and introduced an interface for lxmlDocBase->setDefaultInterlineSpace() in e4841e88c4aec0243f97666219997441807f6ab0. In the same turn I prepared an interface for "setStyleSheet" - but that is untested. In CREngine, line spacing can now be set via Alt+PgUp/Down, where Shift+PgUp/Down is left for font size setting.

**Comment by houqp** [comment]
Great work. I am closing this issue now :)
