### ISSUE TITLE
Release 2012.04?

### ISSUE THREAD

**Issue by hwhw** [koreader/kindlepdfviewer#109]
Hi,

what do you think, should we release 2012.04 soon?

I'd like to add in a key config for launchpad to restart the framework. But that's it for now. Everything else has time until after release, I think. What do you think?

**Comment by dpavlin** [comment]
I think we need some kind of "info" box before slow operations on device (after select file, after search term entry, etc)... In all places where nothing will happen for more than 1s on screen.

We could use same dialog for "no TOC found", "no text for highlight", "no jumpmarks" and so on. Something small in the middle of the screen (using dimRect ;-) might be one possible solution. It should be small, so that screen refresh doesn't impact performance much.

Hack, even write one which displays debugging messages is better than wondering if something happened or not :-)

**Comment by dpavlin** [comment]
We are also leaving child process hanging after fork. I noticed that I can't re-install reader because kpdfview binary was busy. Should we kill child in `closeInputDevices` and waitpid?

**Comment by hwhw** [comment]
Yes, I think so. We should note the PID of the child upon fork() and then kill & wait as you said. I'll give it a try right now.

**Comment by hwhw** [comment]
Added that in 30228890885a34ca470b35238a27598bd9dad914 - however, a lipc-wait-event process is still left dangling until next screensaver/power cycle. No idea right now - I'll see if I find time for that this weekend, but my time is likely limited.

**Comment by houqp** [comment]
> I think we need some kind of "info" box before slow operations on device (after select file, after search term entry, etc)... In all places where nothing will happen for more than 1s on screen.

Can't agree more with the info box.

I am OK with the release as long as #85 is fixed :)

**Comment by houqp** [comment]
Are there anybody still working on new features?

**Comment by dpavlin** [comment]
Left page turning keys on K3 don't do anything

**Comment by houqp** [comment]
> Left page turning keys on K3 don't do anything

Fixed

**Comment by hwhw** [comment]
I think we should release very soon. More and more people are trying out the software, and besides new features there are important fixes in the coming release.

Note that we can always do a 2012.04.1 - if needed.

**Comment by houqp** [comment]
Yes, I am for the frequent release strategy instead of just doing major upgrade. I am OK with the release as long as you guys say OK to #125 ;P

**Comment by hwhw** [comment]
I'm fine with #125, the highlighting can go through an evolution later, I think.

**Comment by dpavlin** [comment]
Release++ Let's make people happy with all improvements :-)

**Comment by houqp** [comment]
#125 closed, @hwhw, when do you plan to do the release with your magical tool-chain?

**Comment by houqp** [comment]
OK, just one more note before I go to sleep :)

All those UIs (filechooser, helppage, etc) which are not using commands module to handle key events will cause striped screen on screen saver.

**Comment by hwhw** [comment]
I'm doing a release ZIP file now, will be in the Downloads soon. In about 18h, I'll update the Download page and update the thread on MobileRead. So we have a small time window to test ourselves.

The optimization of the screensaver handling will have to wait until next (minor?) release.

**Comment by houqp** [comment]
@kljohann just found a bug in jump and bookmark feature ;P

EDIT: I just found some other bugs too, I think we will need a minor release soon. I think next time when we do major release, we can release a beta version first, so active users can help us find bugs.

**Comment by hwhw** [comment]
Nah, I'll do a new ZIP for 2012.04 in a few hours and announce it then. I'll move the tag.

But of course we could do minor releases. Nothing wrong with that at all!

I'm not so sure if the concept of "Beta versions" will work. Our users will start to all use the Beta versions - so they are just "another versions". And we are probably not enough developers to really work in a strict separation of new features / bugfixes.

**Comment by houqp** [comment]
> Nah, I'll do a new ZIP for 2012.04 in a few hours and announce it then. I'll move the tag.
> 
> But of course we could do minor releases. Nothing wrong with that at all!

I am for the minor release, since some of the users already downloaded the 2012.04 release. :)

> I'm not so sure if the concept of "Beta versions" will work. Our users will start to all use the Beta versions - so they are just "another versions". And we are probably not enough developers to really work in a strict separation of new features / bugfixes.

I see. For me, the advantage of beta is to warn people that new features are likely to have bugs so they won't be too suprised when seeing that some part of the software is not working. But you are right anyway, we are short of hackers ;P

**Comment by dpavlin** [comment]
Maybe users could get used to "it's free software - if it breaks you get to keep both parts" and just push periodical zips, just like @houqp does?

I'm more-or-less always running git master version, and aside from short period of instability (which we could mitigate by not building new zip) I think reader is stable enough to have it build automatically from each commit :-)

If we add auto update (tricky, since we need magic HTTP header to pass through Amazon's HTTP proxy on 3G/DXG) we might really push new releases anytime. `this is joke, ignore it :-)`

**Comment by hwhw** [comment]
I've just published and announced 2012.04.1!

Thanks a bunch guys, I'm still having fun - despite doing actual productive work :-P You really rock, I learned to love GitHub and learned a bunch of stuff while working on this.

I think it's one of the fastest, yet easily adapted readers out there. And I use it a lot myself, so it's not just the programming part, but also the "using it" part that is fun.

@dpavlin: Unfortunately, I think non-developers never get used to that :-)

**Comment by houqp** [comment]
Congratulations to all :)

> If we add auto update (tricky, since we need magic HTTP header to pass through Amazon's HTTP proxy on 3G/DXG) we might really push new releases anytime. this is joke, ignore it :-)

I think even an update feature that works in wifi is useful.

> I think it's one of the fastest, yet easily adapted readers out there. And I use it a lot myself, so it's not just the programming part, but also the "using it" part that is fun.

I am using it exclusively now, except for mobi format. And I often find myself pressing `N` when wanting to do highlights in native reader ;P
