### ISSUE TITLE
Left page keys are not bound

### ISSUE THREAD

**Issue by kljohann** [koreader/kindlepdfviewer#128]
There are several places where `KEY_PG…` is used without also checking for `KEY_LPG…`, for example in:

```
crereader.lua
filesearcher.lua
helppage.lua
unireader.lua
```

**Comment by dpavlin** [comment]
`helppage.lua` need rewrite to new event system, and I don't particularly like our usage of `addGroup` for page keys in `unireader.lua` because it's dense code, hard to read and easy to miss adding shortcuts :-)

@houqp I took a quick look at all menu/select like parts of our code, and (at first) it seems to me that there is quite a lot of code duplication there. Do you think it would be doable to create single widget which would handle page buttons (on both sides :-), keyboard shortcuts (by default whole keyboard, but with ability to insert shortcuts into for pages which have custom keyboard commands like help) _and_ fiveway move/select (which we would need to support non-keyboard kindle anyway even in help which might be _only_ was to select zoom level without keyboard)?

I won't have much time to hack on code in next few days, but I wonder how would that turn out, and I'm hoping for some code reduction while providing consistent user experience over different select-list like interfaces in reader currently.

Could such widget call itself to provide help for commands? :-)

**Comment by hwhw** [comment]
I'm on a similar mission right now. I'm further tuning and trying how to make the presentation layer (which I named "Widget") interact with a event handler system. I think in a day I have fleshed something out and will be happily accept comments.

Re-entrance in the program flow is indeed a matter here. Thus the separation of Presentation and Layout. It's a bit difficult: I want to allow widgets to be "active". I.e. they can listen for certain events. They also should allow to change state (e.g. a button can be marked/active or unmarked/active or inactive/not selectable; an input field for text might want to be active and have a special event handling to "catch" horizontal directional movements for managing a cursor etc.).

Eventually, even the document viewer itself would go into a widget. These are big plans, and I would like to illustrate them by investing some hours to create this enhanced Widget (exists in parts) / "ActiveWidget" system, I think.

Maybe it helps to think of the whole application a bit differently. Currently, it is built from a program-flow thinking. That is fine, it makes it clear to follow the path and easily see what happens without having to understand too much abstraction layers. However, our codebase is now large enough to change this advantage. Now it is probably easier to introduce some abstractions to remove the amount of duplicate concepts - and thus duplicate code.

If you looked at the Widget code, you will see that I introduced "lightweight" objects (in fact, tables) to pass data around that belongs together. I do that for a 2 dimensional size, it is { w = <n>, h = <n> }. We have other cases where we have data that we pass around and which belongs together, yet we do it by duplicating something. This is something we could make shinier.

I think if we take a slow approach towards isolating redundancy of code and concepts and create a clear and minimal abstraction, we're best off.

A last thing: The most common factor of our code is an event-handling loop that waits for input. It would be nice if the result of a cleanup would be that there is exactly one single loop persists and everything else fits into this concept.

Now that was a long OT post here. For the matter of this bug, I'd like to add: fixing this now easily by adding the relevant keys is fine. In the end, we better should have an abstraction for keys that mean the same to us :-)

**Comment by houqp** [comment]
Thanks for the report @kljohann , should be fixed in my pull request ;)

I will move the discussion of our new presentation layer and input loop to a new issue.
