### ISSUE TITLE
release 2012.04.2

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#138]
I suggest we do a minor and stable release before we switch to the new UI framework. We have already fixed a couple of bugs now.

**Comment by dpavlin** [comment]
I agree.

**Comment by hwhw** [comment]
Yep, I agree, too. I think the new UI framework is something like a new major release, since it will involve major changes. Don't let that slow down work in the current code - that is also needed. Taking everything to a new UI framework (what I created is only a suggestion for now!) will take a while. I think I will tend to invest time into slow migration. We can do the work parallel in the separate branches. In order to make that easier, I will make some cosmetic changes that leave the API the same for the old code (I broke some minor things when I redesigned, I think).

**Comment by houqp** [comment]
I think the minor release is ready now.

**Comment by hwhw** [comment]
Would be OK for me. I'll do it in approx. 5 hours if noone objects.

**Comment by dpavlin** [comment]
Sure, we'll run out of 2012.04 version otherwise :-)

**Comment by hwhw** [comment]
Released! Thanks a lot!
