### ISSUE TITLE
partial visualization of a page in the zoom_to_fit_page_width mode (landscape)

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#158]
Hi,

there's a bug in the landscape mode.
To reproduce:
1) turn a page (pdf or djvu) counterclockwise
2) select the zoom_to_fit_page_width mode (press 's')

As a result, only the middle part of the page is shown.
Pressing the forward/backward buttons jumps to the next page.

**Comment by vmonkey** [comment]
Agree, however for me it seems not so easily reproducible - for one of my files this happens only on 5th page, on others not.

**Comment by eLiNK2gl** [comment]
Hmm, on my KDXG I have this problem with every single file (I checked 7 files in total).
I'll do a clean install of the last release and report back.

**Comment by eLiNK2gl** [comment]
Have done the clean install, the problem persists.

**Comment by dpavlin** [comment]
I can reproduce this is emulator using

```
EMULATE_READER_W=1280 EMULATE_READER_H=1024 EMULATE_READER=1 make kpdfview
```

since we don't really have screen rotation under SDL (which I should appreciate, @hwhw hint, hint ;-)

**Comment by dpavlin** [comment]
From reading code, it seems that @eLiNK2gl, @vmonkey are expecting behavior which is `ZOOM_FIT_TO_CONTENT_WIDTH` and bound to `shift`+`s` instead of just `s`, which is `ZOOM_FIT_TO_PAGE_WIDTH`

I was under impression that page zoom modes don't mess with previous/next keys while content zoom modes do, so I don't think this is really a bug. Maybe a documentation update?

**Comment by hwhw** [comment]
I hope that I can get back to the code this weekend. New Laptop over here, I need to fiddle a bit to get everything running again. And SDL rotation is on my list. Maybe even custom resizing, too, but that would not be easy to integrate into the software for now.

**Comment by dpavlin** [comment]
I would love to implement continuous pages mode, but it seems I will be quite busy during next few weeks, so I can't promise anything... I still have to dig into new ui branch, so I can wait, no problem :-)

**Comment by dpavlin** [comment]
This code is not really intended for merge, but might show nicely how to debug reader by instering debug statement here and there...

**Comment by houqp** [comment]
> I was under impression that page zoom modes don't mess with previous/next keys while content zoom modes do, so I don't think this is really a bug. Maybe a documentation update?

That's it. The problem here is it necessary to make these fit to page mode work like fit to content mode?

Aha, I also want to bring highlight support from crengine and play with the new UI framework. But I am on travel tomorrow for a couple of weeks. I only have a netbook with me on the road, so I guess I won't have time for coding ;P

**Comment by vmonkey** [comment]
I am not sure if this issue was understood correctly. So I will try to explain it once more.

1) Open this file: http://ubuntuone.com/3M757qU3CAVLjuZiGtAeYv
2) Because it is not readable in portrait mode, do a rotation using J.
3) Since I now want to have the page larger, I just press S and then navigate inside the page using fiveway. Everything works. To get to next page I use > button.
4) On the fourth page panning suddenly stops working - may it be because of another resolution of the fifth page?

I think that it has to be bug because the fourth page is not anyhow pannable (like the others). However, I am sure that it is not always reproducible bug (at least once I got it working properly, but I am not sure how).

EDIT:Heh, I just realised that this should have been reported as another issue, I just misunderstood it somehow.
