### ISSUE TITLE
NuPogodi patch: How to integrate?

### ISSUE THREAD

**Issue by hwhw** [koreader/kindlepdfviewer#166]
Hi,

here @NuPogodi published a patch: http://www.mobileread.com/forums/showpost.php?p=2080025&postcount=380
It has some nice things, however, it's not easy to separate the new functionality and I'm having a hard time figuring out how to integrate it... Ideas?

**Comment by houqp** [comment]
Um... maybe we can create an other branch for his patched version so we can do some reviewing and gradually integrate the changes. It will be a lot better if we can persuade him to join us in github :)

**Comment by dpavlin** [comment]
I tried to checkout version on which this patch is based and copy all changed files over to create branch with changes. However, since most of code also does some re-indenting this created large and wrong diff. Then I tried to make diff -w (which should at least ignore white-space changes) but that patch failed to git apply (although it was generated by git itself).
