### ISSUE TITLE
suggestion for using table serialization in settings module

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#17]
hi HW,

please refer to:
http://www.mobileread.com/forums/showpost.php?p=1979888&postcount=73

any comments on this post?

**Comment by hwhw** [comment]
Yep, read that :-) I agree. SQLite just was the first hammer that got near me, so I took it. At that point I still wasn't sure whether per-file data storage is a good idea at all. I'm still not definitely decided on that. The monolithic approach (a single DB for all documents) has its charme, too. But speed is a good argument here.

In the back of my head I also had a vague idea of using the database for storing extracted text. Probably, this idea is silly since this text can be generated by just accessing the PDF document anyway and it's not clear that caching it will improve speed.

**Comment by houqp** [comment]
I think per-file data storage is better for storing book settings. Not just faster to parse, but also easier to maintain. For instance, when user wants to delete a book, they only need to delete the whole folder. 

And you are right, single DB has its charm. The native system is super fast in searching. I don't know how they made it.

An other solution might be using these two approaches at the same time. Handle per-file data storage with table serialization and use sqlite3 for single DB if needed.

**Comment by dpavlin** [comment]
I'm all for human-readable serialization per-document. This would allow us to store annotations (once we have them ;-) in same file and allow easy transfer to other device or machine.

**Comment by hwhw** [comment]
I've switched over. Also disabled compiling of SQLite for now, we can add it back when we need it later. The serializer is self-written, since I found none with a proper license (and did not like the output of some which had a proper license). It's quite simple, but it should work OK for our purposes.

**Comment by houqp** [comment]
Just use it to save jump stack, works like a charm! Now I can edit these settings with Vim. :-)

**Comment by hwhw** [comment]
Closing for now, we can re-open this issue when, well, issues arise :-)
