### ISSUE TITLE
on-screen keyboard should default to lowercase chars and support shift

### ISSUE THREAD

**Issue by dpavlin** [koreader/kindlepdfviewer#194]
With recent changes in our on-screen keyboard it always starts with capital letters as default. It makes it suboptimal in my opinion, because I first have to switch to lowercase letters to enter anything.

I'm writing this issue instead of providing patch because I did try to modify layout in inputbox.lua, but failed to make it default to lowercase chars. In the process we also lost ability to enter uppercase characters using shift keys. I don't understand enough of inputbox.lua code to make this change mysql, maybe @NuPogodi can help me out with this one?

**Comment by houqp** [comment]
Agree, I also prefer lowercase as default layout ;P

**Comment by houqp** [comment]
Just figured out a dirty hack: change the argument from nil to 3 in following line:
https://github.com/hwhw/kindlepdfviewer/blob/master/inputbox.lua#L341

As for shift support, I think it is better left to @NuPogodi....

**Comment by ghost** [comment]
That's correct place, but it would be better to write here self:addCharCommands(self.layout) and set the default value in the header as InputBox = { ... layout = 3...}. In this case, you may eventually set any (!!) default layout with the external calls like someBox = InputBox{ layout =XX }
The shift support? Do you mean the simultaneous Shift+Char = Capitalized Char? I'll think about it... But I've actually wanted to leave Shift+Char for hotkeys (say, Shift+P = screenshot, etc) and to enter capitals by switching layouts with the CapsLock = KEY_AA

**Comment by dpavlin** [comment]
I played a bit with a code and it seems to me that shiftmode has true for lowercase and false for uppercase chars... Shouldn't it be other way around?

**Comment by dpavlin** [comment]
I would expect for Shift+Char to produce capital letter. We could probably use alt for shortcuts but we would have to make than consistent between file-chooser and other reader implementations.

**Comment by ghost** [comment]
ATM, the shiftmode=false does result to the 2nd layout, shiftmode=true > the 3rd one. This arrangement (and the comments as well) remains just for historical reasons since from the very beginning I typed the small chars in the 2nd layout, the capitals were in the 3rd (i.e. vice versa). Then I've toggled the layouts (in the way like they are now) just to make small chars & digits to be the neighbor layouts. The reason was I've used these two layouts in my small calculator based on the code of inputbox.lua (I've already told houqp about calculator & about my doubts that it is worth to implement in the master branch)
BTW, I've also fixed help support and added two additional commands to inputbox.lua - (i) move cursor to the 1st position and (ii) to the last position (just to avoid multiple FW-left & FW-right pressing)

Concerning the Shift+Char = capital letter... It is not so complicated: one to control control pressing Shift and, when it is pressed, just redefine the char commands (and maybe redraw the virtual keyboard layout). One should first redefine all the hotkeys (Alt-H for helppage, Alt-F = fonts, Alt-S = search, etc) in other lua-files anyway.

**Comment by dpavlin** [comment]
My current solution for default lowercase chars include changing `shiftmode = true` in https://github.com/hwhw/kindlepdfviewer/blob/master/inputbox.lua#L41

@NuPogodi is that OK? Can I submit that change for master?

**Comment by ghost** [comment]
You may select default lowercase layout either via integer 'layout' or via its bits (shiftmode, symbolmode & utf8mode). The former requires to write self:addCharCommands(self.layout) in line 341 & layout = 3 in line 39, the latter should work if the rest of code remains "as-is" Both methods are quite acceptable.

**Comment by ghost** [comment]
I've just uploaded new version of INPUTBOX:LUA to my repo https://github.com/NuPogodi/kindlepdfviewer. 
If someine is going to use inpubox also as calculator, one needs to introduce minor changes to HELPPAGE.LUA (so I've also refreshed this file in my repository).
Alternatively, both lua-files and the description of all changes is uploaded elsewhere http://rghost.net/40063033
I hope that that should solve most of the mentioned above problems...
