### ISSUE TITLE
No conversion to 8bpp takes place while making screenshot

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#215]
Screenshots are made in raw format.
Thus, a conversion is necessary to some wide spread formats (like jpg or png).
But the raw files are in 4bpp and there is no (known) software, which can tackle 4bits per pixel.

P.S.: The file k3rawto8bpp.exe (in kindlepdfviewer\screenshots) serves to address the issue and could be used in Windows.

**Comment by dpavlin** [comment]
FWIW, here is script which converts framebuffer dump into pgm: https://github.com/dpavlin/k3libre/blob/master/fb2pgm.pl

**Comment by ghost** [comment]
I've once tested the Lua-based convertions (both 4bpp.raw > 8bpp.raw and 4bpp.raw > 8bpp.pgm) and has been definitely disappointed by too large Kindle3 CPU-time (2.5-3s) needed for it. This value should be appox. twice as large for KDX(G) because of larger number of pixels. Besides, such a convertion duplicates the filesize so that one also has to compress the output screenshot - for example, os.execute("bzip2 "..filename) results in ~15KB for 8bpp.raw.bz2 instead of 472K for 8bpp.raw.
Conclusion: it has no sense to do it with Kindle, PC fits this task much better - the C-source was already published http://www.the-ebook.org/forum/viewtopic.php?p=902190#902190 , it could be readily compiled for any OS. 

[UPD] If one just needs common-accepted screenshot formats, one may take this version of https://github.com/NuPogodi/kindlepdfviewer/blob/master/screen.lua 
It saves screenshots to the plain (or bzip2-compressed) bitmaps and (since no colorspace conversion is implemented) makes it relatively fast.

**Comment by ghost** [comment]
I've written and compiled few executables that save the framebuffer content to various graphic formats - namely, screen2bmp, screen2tiff, screen2pgm & screen2png. So, the lua-code (previously included in screen.lua) might be readily replaced by simple calling of os.execute(lfs.currentdir().."/screenshots/screen2xxx")
The c-sources & compiled executables are uploaded here http://rghost.net/40064856
ATM, all executables (except for screen2png) produce uncompressed images and hence relatively fast (they also produce small log-files where the consumed CPU-time is included). Besides, these executables (again, except for screen2png) should properly work for all Kindle models including 8bpp-devices (K4NT & KTouch).
screen2png is a bit different. It is written on the basis of lodepng by Lode Vandevenne http://lodev.org/lodepng/ , it uses intrinsic compression and pays for this compressed png-files with the CPU-consumption of 1-2s on my Kindle3.

Finally... I think it would be reasonable to add the following code

obj:add(KEY_SPACE, MOD_ALT, "Space",
        "make screenshot",
        function()
            showInfoMsgWithDelay("making screenshot...", 1000, 1)
            os.execute(lfs.currentdir().."/screenshots/screen2shot")
        end
    )

to function Commands:new(obj) in COMMANDS.LUA (it also included in http://rghost.net/40064856) that allows us avoiding the code duplication in existing lua-modules (where screenshot feature has already been implemented) as well as in any future lua-files with hotkey commands.

**Comment by dpavlin** [comment]
While I do see benefit of separate utility to do screen-shots (which might be useful outside kpdfviewer) I'm wondering do we need to introduce another dependency since we already have libpng as dependency.

I would love to hear other opinions on this...

If would make sense to make screen-shot keyboard shortcut at one single place.

**Comment by tigran123** [comment]
@dpavlin IMHO, the Lua code which @NuPogodi wrote for making screenshots in bmp format is perfectly adequate (btw, the other format function can be safely deleted --- bmp is more than adequate and can be converted on the computer to any other format if needed).

Therefore, I would vote _against_ invoking external utilities (even very simple ones) and would prefer to rely on the Lua code for making screenshots.

**Comment by tigran123** [comment]
Is it the consensus of everyone that the way screenshots are done currently (in Lua) is the best way, so we can safely close this issue?

**Comment by dpavlin** [comment]
+1 for close
