### ISSUE TITLE
Crashing crengine on corrupt .zip files.

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#314]
CREReader:ZipContentExt() or (more likely) the caller thereof should be strengthened to handle corrupted zip files, i.e. not crash the whole application but print an error message and go back to filechooser.

**Comment by ghost** [comment]
My previous version of CREReader:ZipContentExt() you recently modified was successfully tested on zips with not crengine-related file entries and non-zip files with zip extention. I've never observed crashes of the reader, the proper error -- either about improper zip content or unzipping error -- was displayed instead.

Please, provide, the corrupted zip file that causes kpdf to crash so that I could reproduce it and try to fix the problem.

**Comment by tigran123** [comment]
There are actually two problems there: 1) my fix broke the code path leading to "Error unzipping file." and 2) the io.popen() was used not in the best manner. As I broke it, I'll fix it, please wait.

**Comment by tigran123** [comment]
Actually, in your old version there was another bug as well, it would crash crengine on certain invalid zip files. Anyway, please wait, I'll cater for all these instances and then we can test out the result.

CORRECTION: the above comment is incorrect --- it was crashing because of my added debug code and not the original. I will restore the original plus a couple of necessary changes in a minute.

**Comment by tigran123** [comment]
Closing the issue as the fix is in the pull request #315.
