### ISSUE TITLE
links in crengine not implemented

### ISSUE THREAD

**Issue by kaysin** [koreader/kindlepdfviewer#403]
i cant open the links in mobi on dxg. ..  i can see underlines with those links .. but ,when i use hotkey _L .. kpv said no link on the page .

**Comment by tigran123** [comment]
local links are only supported for PDF files. Those underlines you see are not coming from KPV but from the mobi file itself (which is a bit confusing, I agree).

**Comment by dpavlin** [comment]
I will re-open this issue to have placeholder for this improvement.

I did try to add links for crengine while I was implementing it for mupdf, but crengine doesn't have built-in way to return links, but can return link under some point on screen. I wouldn't want to implement some kind of cursor for crengine, so I have to understand crengine DOM manipulation a bit more before I can submit code to implement it.

**Comment by houqp** [comment]
@dpavlin , just a side note. If I remember correctly, cregine comes with its own cursor implement, which might save you some work. But I might be completely wrong. ;p

**Comment by dpavlin** [comment]
I gave my code another go, and it seems that I understand enough of crengine API to wrap up something https://github.com/dpavlin/kindlepdfviewer/tree/cre-links

I'm not using cursor support because I want to have multiple shortcuts selectable at the same time, just like we do for mupdf. For touch-based devices there is much nicer API in crengine which allows to get link under cursor.

It's very rough, which is why I'm not submitting pull request for it. I will have to split parts of code from unireader to implementation specific subs instead of depending on structure to figure out where data is coming from.

**Comment by tigran123** [comment]
Oh, is it supposed to work with chm files as well? I have some interesting Encyclopedias and other books in chm format which are unusable because of the links, but if your code will give them life then it would be great! :)

**Comment by tigran123** [comment]
Pressing `L` on the Lua 5.1 Reference I get

```
## pos=0
# link 0 start 76 43 end 76 43 '' http://www.lua.org/
# link 1 start 20 287 end 20 287 ' ' http://www.amazon.com/exec/obidos/ASIN/8590379833/lua-indexmanual-20
# link 2 start 48 499 end 48 499 ' ' http://www.amazon.com/exec/obidos/ASIN/8590379833/lua-indexmanual-20
# link 3 start 344 533 end 508 533 'help to support' http://www.lua.org/donations.html
# link 4 start 397 645 end 85 673 'Programming in Lua' http://www.lua.org/docs.html#books
# link 5 start 48 701 end 98 701 'start' #_doc_fragment_2
# link 6 start 116 701 end 209 701 'contents' #_doc_fragment_1_contents
# link 7 start 227 701 end 286 701 'index' #_doc_fragment_1_index
# link 8 start 304 701 end 415 701 'português' http://www.lua.org/manual/5.1/pt/
# link 9 start 433 701 end 518 701 'español' http://www.lua.org/manual/5.1/es/
# link 10 start 217 776 end 312 776 'Lua license' http://www.lua.org/license.html#5
lua config error: ./rendertext.lua:30: attempt to index local 'face' (a nil value)
```

**Comment by dpavlin** [comment]
Yes, it should work for all crengine formats. I rebased it on top of current muster, and removed few commits at beginning which where my experiments with code. New branch is at: https://github.com/dpavlin/kindlepdfviewer/tree/cre-links-cleanup

Shortcuts are shifted to the left, and I couldn't find any reference to page margins in crengine expect getting style of element which might have margins, but that seems wrong to me. @houqp do you have any idea why coordinates from crengine are shifted to left (e.g. start from 0 and not from first pixel of text)

I don't know if I should submit pull request of all commits of just squash it in single one. I'm biased towards single, since this is one huge change, but if you find individual commits useful, I will submit it as-is.

There is also build from this branch at: https://github.com/downloads/dpavlin/kindlepdfviewer/kindlepdfviewer-v2012.09-193-g7bf9fad.zip

**Comment by houqp** [comment]
um.. I also took a quick look on the get link method and seems that it does not involve any margin calculation at all. I think it kind of make sense as CREngine fetches the absolute/original link coordinates inside document without any margin calculation involved. This makes the link data structure static, so when user changes the style of the document, we don't need to fetch all the link information again.

We might want to take a look on how CREngine draws selections for the links. Have you checked the `LVDocView::selectPageLink` method?

**Comment by tigran123** [comment]
Implemented now, so we can close this.
