### ISSUE TITLE
Page redraw missing when setting file manager's mode in the readers

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#404]
This function was added recently and has an obvious bug as described in the subject.

**Comment by tigran123** [comment]
The same broken behaviour when pressing `I` in the reader. The code is:

```
Screen:saveCurrentBB()
FileChooser:changeFileChooserMode()
Screen:restoreFromSavedBB()
```

so, looks like the save/restore BB functions don't really work in that context.

**Comment by tigran123** [comment]
Replacing the above with the old-fashioned:

```
FileChooser:changeFileChooserMode()
self:redrawCurrentPage()
```

makes it work fine, but I'll leave it for someone who knows about saving/restoring the bitblit buffer stuff more...

**Comment by houqp** [comment]
In deed, I don't recommend using save and restore BB methods to update screen. Because it does not check the content of the BB, which means it might restore a wrong BB (and it often does). The reason I add these two calls is just to help with screen saver hack. So call self:redrawCurrentPage is a better practice.

**Comment by tigran123** [comment]
Ok, thank you, I will do a PR then.

**Comment by tigran123** [comment]
Fix was merged into master, closing the issue.
