### ISSUE TITLE
Request : column zooming function for manga

### ISSUE THREAD

**Issue by melib** [koreader/kindlepdfviewer#453]
Could you enhance "zoom to first column function ('F' and 'shift+F' keys)" in reader mode to be able to start at "a top right corner" or "a top left corner"?

So that I can choose "start at top right corner" when reading two-page manga and "start at top left corner" when reading two-column journal.

Two-page manga, for example, http://www.mangaforkids.com/images/howto-spread.jpg

Thank you.;)

and sorry for my English.

**Comment by dpavlin** [comment]
Do you have any manga document with more than one page? From my limited knowledge about Japanese I would also assume that you start reading on last page and move toward first one (from my western point of view, that is ;-)

Current code have some corner cases where margins won't work well (pdf files from Linux Journal are example for me) so I was thinking about fixing that, so I will also have in mind this feature request when I start working on it.

**Comment by tigran123** [comment]
@dpavlin Yes, that would be syntactically correct for Hebrew (and other semitic languages like Syriac, Aramaic, Arabic, etc) but I wouldn't advise to mix this in with the right-to-left column switching mode. The reason is because many books have right-to-left columns but when they are provided in PDF or DjVu formats they actually start from the physical page=1 and not from page=lastpage. This is for the "user's convenience". So, I suggest keeping the right-to-left column switching and right-to-left book binding separate.

(I don't know about Japanese "manga" documents, but a Google search reveals that yes, those are read from right to left and start at the end of the document, not the beginning, but this, imho, is of minor relevance compared to the above argument)

**Comment by tigran123** [comment]
I would also like to add that PDF specification provides an object which tells which direction (R2L or normal) it is typeset in. My typesetting system actually makes use of it (for right-to-left semitic languages), but most viewers ignore it anyway...

**Comment by melib** [comment]
@dpavlin This is a sample. http://www.mediafire.com/download.php?vwcw3d3gy59mhfl 
Each page is merged from two pages and Texts is too small for reading even reads in landscape mode.

Page ordering is not problem for reading manga in kindle because It reads normally from the first page to the last page.
But it reads from right to left in each page so if  the zoom function can start at the top right corner, It would be awesome.   

Thank you very much.

**Comment by kai771** [comment]
Now I see this was discussed here, so I shouldn't have opened #515. I'm no expert (far from it), but I'd like to add a few comments about japanese "start reading on last page and move toward first one" and clarify a possible misunderstanding.

Instead of thinking that japanese "start reading on the last page", think like this. If you're a westerner, you'll bind your freshly printed stack of papers on the left. If you're a japanese, you'll bind it on the right. The order of pages is the same, it's the position of the binding that's different. That's why when put in pdf pages are normally ordered. Thinking that it should be "first page as the last page" is merely a thought influenced by westerner's custom of binding books on the left.

**Comment by dpavlin** [comment]
@kai771 thanks for implementation. I'm quote busy at the moment, so I really appreciate your effort on this issue.

**Comment by melib** [comment]
Thank you kai771 for your hard effort, however, I couldn't test your work because I have broken my kindle.

**Comment by kai771** [comment]
@melib Sorry to hear it. I hope you get it fixed/replaced soon, so you can enjoy reading manga :)
