### ISSUE TITLE
pdf fit width mode and page down button

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#457]
The fit content width mode have been improved that page down button will move to the remaining part of the page, instead of the old behavior which jump to next page directly.

However, the fit width mode is still showing the old behavior, i.e. user can only use five way to move bit by bit for one page. Most of time fit content width can replace fit width mode, but sometime kpv have some difficulty recognize the correct content width, and the fit content width mode will have some part cropped outside so I have to use fit width mode.

I think the fit width mode should have the same behavior with fit content width mode, i.e. use page down to move to the remaining part of same page if that page is not displayed completely, and move to next page if the current page have been displayed completely.

**Comment by tigran123** [comment]
@dracodoc There is no real problem here because you can (and should) ONLY use `Shift-S` mode in conjunction with `Shift-X` mode twice, i.e. for one page and the next, thus defining bbox for both odd and even pages. With this in mind, the "fit width mode" (`S`) is actually irrelevant and could be removed altogether. We just didn't bother removing it because... well, I suppose we just didn't bother, that's all :)

So, the suggested usage of `Shift-S` mode is like this:
1. Delete the history file for the book you are about to read (as it may contain the old bbox values which will interfere with the following steps).
2. Press `A` to see the full page
3. Press `Shift-X` and set the boundaries (top-left and bottom-right) of the bbox appropriately, for ideal reading experience.
4. Press `Next` to go to the next page.
5. Press `Shift-X` and do the same for this page also.
6. Press `Prev` to go back to the previous page (assuming that is where you want to start reading).
7. Press `Shift-S` and enjoy reading.

**Comment by tigran123** [comment]
@dracodoc Just to clarify further than I don't disagree with you that page `Next/Prev` should behave in `S` mode exactly the same as they do in `Shift-S` mode. I totally agree with you on this. I am simply saying that there is no need to use `S` mode at all --- with the properly configured bboxes via `Shift-X` the only two modes that you need are `Shift-S` (for single column books) and `Shift-F` (for two column books). Btw, likewise the `F` mode is irrelevant and could be deleted.

And since I mentioned two column books let me add that the procedure to prepare such a book for reading is almost the same as the above for single column with the following differences:
1. Instead of `Shift-S` you press `Shift-F` to start reading
2. When you use `Shift-X` to configure bbox make sure you cover BOTH columns, not just one!
3. Instead of `Next/Prev` buttons to move around the page you press the fiveway `Up/Down` to move up and down the current column and fiveway `Right` at the bottom of the left column to go to the top of the right column and at the bottom of the right column to go to the next page (i.e. to the top of the left column of the next page). And you use `Left` at the top of the right column to go to the bottom of the left column and at the top of the left column to go to the bottom of the right column of the previous page.

So, now you have complete descriptions of the procedures for optimal reading of both one-column and two-column books. Enjoy, my friend! :)

**Comment by dracodoc** [comment]
Thanks, now I know how to use shift-X and shift - S... I didn't know the "content" is defined by the shift- X, because when I use shift - S before most time kpv can get the content box right, so I thought it was all automatic, don't need user interaction. I just saved this page. Can you add your description to the wiki? I bet many user don't know how to properly use shfit-x...

That being said, I don't think "fit page width" mode is totally irrelevant. With Shifit - X you do can get any effect you want, if you define the page box at the edge, that will be just like "fit page width". However it take some time to define the page box, right? While if the book page margin is appropriate or user has cropped it before put it to reader, the "fit page width" mode could serve the purpose without any configuration time. Consider the cases that some pages have special format different from most pages, like the first page of each chapter, Shift -X method may need to further customize page box for them, while the "fit page width" could be good enough, although not as perfect.

**Comment by dracodoc** [comment]
Just thought about another usable feature: 2 screen for 1 page mode.
With kindle DX, even the pdf with smallest font should be able to be read comfortably in landscape view. However, the fit width mode currently will jump to next page directly with page down, and fit content width mode need to manually define crop box with shift x -- one reason I never use crop in kpv before is that I've cropped the pdf in pc in most cases. Even with shift-x, sometimes one page may need to be displayed in 2 and half screens, or 1 and half screens.

So I'm suggesting a 2 screen for 1 page mode, in this mode kpv take the page height and split it into 2 screens, make each page exactly 2 screen. This mode will not get the maximum usage of screen like shift-X and fit content width, but it will make each screen looks better. Especially in rotated mode/landscape mode, I estimate most pdf will have good enough zoom ratio to be read comfortably.

Update: upon further consideration, this mode has its flaws. The half page may be not suitable for one screen, i.e. too wide for screen width. The perfect solution will be the scroll mode which will solve all these problems.

**Comment by houqp** [comment]
@dracodoc , do you mind moving your 2 screen for 1 page mode to a new issue?

**Comment by dracodoc** [comment]
No problem, but I thought it will only be suitable for limited cases. The perfect solution is still the scroll mode, so maybe you can just ignore this feature suggestion.

**Comment by tigran123** [comment]
Yes, I agree with @dracodoc that this feature suggestion should be ignored. Let's just do that --- and it requires no change to the code :)
