### ISSUE TITLE
Non-ascii characters in djvu file name crashes kpdfviewer

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#47]
eLiNK has found the causes the crash in issue #39. Please see his message below:

> I believe I found the source of the problem.
> All of the files I tried to open contained some of the german specific letters (like ä,ö,ü, and ß).
> As soon as I renamed one of the files (e.g. Strauß.djvu -> Strauss.djvu), I can open djvu files as well.

If I run kindlepdfviewer from ssh, everything goes fine. But when I run it with launchpad, it crashes when trying to open a djvu file from file browser.

I guess this bug might affect file name with characters from other languages as well. Just checked with Chinese file name and it crashes too. 

Pdfs are not affected though.

**Comment by hwhw** [comment]
Ah. It's djvulibre. Somehow they decided to put an abstraction for URLs in place. They fitted regular files somehow half-baked into that model (sorry, no offense meant) and thus have a distinction for UTF-8 based file names.

On the kindle we have UTF8 based file names. So I guess it's just a matter of replacing ddjvu_document_create_by_filename(...) by ddjvu_document_create_by_filename_utf8(...). I'll commit a patch right now. But I'm not quite happy with it, because it's common knowledge that you shouldn't mess with filenames and just present to the OS what you got from it. Actually displaying file names is a different matter, though.

**Comment by houqp** [comment]
Um... Just tried the fix, it did not fix the crash. I don't understand why these utf-8 file name does not crash the reader when the reader is invoked from command line. What is the difference between running the reader in command line and with launchpad?

**Comment by hwhw** [comment]
Hm, if I have to guess I'd say it's probably an environment variable then. But then I really need to analyze it carefully, i.e. insert some debug output...

**Comment by houqp** [comment]
Ha, you are right! Just checkout the environment variables. ;-P

Fix added in my pull request.
