### ISSUE TITLE
jump to items by keyboard shortcut in last read history, maybe even in everywhere

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#508]
One advantage of kindle keyboard is we can use keyboard to jump to certain item in a list directly. This feature has been implemented in many places in kpv, can we make it a universal feature available for every possible list?

Right now the last read history don't have keyboard shortcut, so it could be rather cumbersome to select one item in a list, which compromised the purpose of the list itself.

**Comment by tigran123** [comment]
I have already explained in the past why this is a bad idea.

The history list is part of the filemanager, i.e. it has the same functionality (e.g. running a program, pressing `Right` to get info, etc), so it should have the same look and feel as the normal file list. And the latter certainly should NOT have any keyboard shortcuts because that would waste valuable horizontal space that is used for two things: a) the icon signifying what file type it is and b) the filename.

Now, concerning navigating the list this is, as always, a matter of user education, i.e. perhaps you (like 99.9% of users out there) did not realize that you can use the following keyboard shortcuts _now_ to navigate any of the filemanager's lists (including Last Documents of course):
1. Page Up/Down
2. Numbers (Alt-Q... Alt-P) to jump to 10%, 20%,... 0% of the list instantly
3. `G` key to go to a specified page number (total number of pages is shown at the bottom)

So, in the very worst case you would have to press fiveway `Down` key 10 times to get to the entry in the middle of the list. If it is closer to the bottom then you can press PageDown and then fiveway `Up` to reach it quickly.

**Comment by dracodoc** [comment]
Sorry I didn't realize this is a part of file manager. Then I understand it's not a good idea to use keyboard shortcut to jump in this list.

Though I would suggest to modify the help page a little bit, because in other places when user are told to press number he can press the key directly without using alt modifier, but he need to use alt modifier in this case which is understandable, though it'll be better to be more clear about this in the help page.

I'm thinking add "Press Alt+first line of keyboard" to the help message on using numbers to jump, what do you think?

Actually there are already plenty of methods to jump to certain location right now, I just didn't study the help page enough:
1. using numbers
2. press s to search, which can filter result quickly
3. just press and hold the five way button, the cursor moving speed is fast enough.

Do you think it's appropriate to add some tips in the help page? KPV have LOTS of features and functions, I consider myself a power user at least, I bet many users will not find the full power of kpv by himself...

**Comment by tigran123** [comment]
I agree that we should have all the information recorded somewhere. If there is no space in those one-line descriptions in the Help page then we should write a good detailed KPV User's Guide. And this is not just to describe the existing functionality but also to get rid of superfluous functionality which sits there for historical reasons but nobody really knows what it does and why it is still needed. E.g. I don't understand why we need any of `Z`,  `Shift-Z` or `Alt-Z` commands. They seem useless to me and imho should be thrown away. But presumably they serve some mysterious purpose...

**Comment by dpavlin** [comment]
`Z` was useful before we had `X` user interface to select bounding boxes (it selects current view for bbox) but nowdays `X` is much better option. And we can get additional key for something else...

**Comment by dracodoc** [comment]
@tigran123 Do you think it's easy to add sorting support in this "last documents" list?

KPV support folder based organization, if the "Last documents" list can be sorted by "recent read", "reading progress", that will be great. Thus it can provide a useful view for user even lots of books have been opened.

**Comment by tigran123** [comment]
@dracodoc Yes, it is done already. It is sorted by "the most recently opened" order.
The only "catch" is that you have to leave "Last Documents" dialog and re-open it to re-sort it.

Maybe we should make `SPACE` to force re-sorting. Or even simply returning to it from opening a document should re-sort it....

Or, maybe, the current behaviour is more convenient? Let's think about it... 

Do you really want all the files jump up and down after you re-open some files? I.e. visually you would always see a different list and it may be confusing. I.e. it may be actually more convenient to keep showing the same list UNLESS you choose to close the "Last Documents" and re-open it --- then it will be shown in the current "most recently opened" order.

**Comment by dracodoc** [comment]
@tigran123 Do you mean the order is not only based on "recently opened" but also on the frequency of opening? 

Because I noticed that if book A, B are both in the list and in order of "A-B", opening B then close will not move B to the top of the list. So it seemed to me it is not sorted totally by "recently opened". The current order is fine to me, if the list changes for every new opened book, it will not be easy to follow. 

Another possibility is to have a favorite list. Of course user can move books to a special folder to have similar effect, but an ideal organization will be organize books by category into folders, and pick current reading books or important books to favorite list.

I know there is no need for a complex collection system, the current file browser works fine. However I think a favorite list could be simple enough and useful, and not to add too much complexity to current system.
