### ISSUE TITLE
a suggestion on "KEY_SPACE"

### ISSUE THREAD

**Issue by kkzxak47** [koreader/kindlepdfviewer#513]
I'm using a Kindle DXG. I read a lot of scanned books and I'm used to read them horizontally.('K' and 'Shift + S')
Wondering if "SPACE" could be defined as page forward in this situation. And 'V' or some other key could be defined as page backward. This is much more handy, don't you think?

In comparison with that, 'refreshing manually' is not that useful for me...

**Comment by dracodoc** [comment]
There had always been a plan for user customization of keys in new framework. I don't know when that can be done (myself would change a lot of keys if possible), though you can change the key mappings in keys.lua right now as a hack. It will change the mapping globally so maybe not perfect for your need.

**Comment by tigran123** [comment]
@kkzxak47 I think until we have user-customizable keys this suggestion is not going to be acceptable, because some people may not like your choice and we can't please everyone.

Closing this issue, and if you wish you can open another one with a more generic request to provide user-customizable keys as a new feature.
