### ISSUE TITLE
Self-documenting keyboard shortcuts

### ISSUE THREAD

**Issue by dpavlin** [koreader/kindlepdfviewer#55]
Motivation:
- inline documentation for keyboard shortcuts within code itself (for easy maintenance, instead of wiki which we would need to render to pdf to somehow provide as help file in reader)
- provide menu from which users can review shortcuts or select them if they are on device without keyboard (I had Kindle 4 without keyboard in my handles, and it took me a while to figure out that even if I knew how to start our reader on it, it would still be useless)

I propose to write  function called within if/else/end code in unireader.lua file this:

``` lua
key_help("Alt+F","zoom without margin",ev)
```

This function would populate key_help_overview lua table in sequence in which functions are called. That table would be saved on reader exit, providing quick review help file.

This approach has several advantages: while you are developing you will press all new keyboard shortcuts, thus creating correct help file and ability to edit it allows easy creation of "simplified" readers.

Also, since help is added in sequence in which keys are pressed (during development) this allows logical ordering instead of alphabetical one if we depended on key sort order.

Another possibility is for key_help to also display feedback to user.

Last parameter ev is needed to record correct keypress which generated help message, so we can implement fake events correctly.

**Comment by hwhw** [comment]
Oh, the reader, errr, works on the K4NT? Nice. OK, then we really want something like that. Probably, we'll want everything that has a shortcut in a menu as well.

I'm not sure whether we really need that if/then/else. I guess we can use a function like you proposed to generate dynamic Lua code that we can loadstring(). Although that would already be an optimization. We might just replace that if/elseif/elseif/... by a bunch of calls to such a function.

Dropping the if/then/else would allow for concentrating the parsing of keys in a single function.

I.e.:

onKeyCombo(ev, "Alt+F", "zoom without margin", function xyz () ... end)
onKeyCombo(ev, "...", "<doc>", handlerFunction)
...

I'm not sure what you meant why you wanted to pass ev to the function. In the above example I would pass it to check the key combo against.

**Comment by houqp** [comment]
Ha, also curious whether the readers works in K4 :)

Just a little note.  Since shortcuts is every where (readers, menus, filechoosers), we might need to put all these into a separate module that focus on handling key events.

If we can have this kind of module, we can even just register handler functions to key combo in that inputloop module. Then on every key event, we just need to pass the `ev` to the inputloop module, nothing more.

**Comment by dpavlin** [comment]
I didn't actually _run_ reader on K4NT, mostly because my time with device was limited to several hours, so I just managed to get ssh access in diag mode and then I run out of time (and then noticed missing keys ;-)

**Comment by houqp** [comment]
> I didn't actually run reader on K4NT, mostly because my time with device was limited to several hours, so I just managed to get ssh access in diag mode and then I run out of time (and then noticed missing keys ;-)

LOL. Does K4NT has a 8bbp or 4bbp framebuffer?

**Comment by traycold** [comment]
just a thought about the issue: if we implement a function like
`define_shortcut(key, modifier, function_to_call, help_message)`
then, we may be able to solve the issue of providing a sort of help page, and at the same time we wouldn't not modify the input_loop whenever a new feature (shortcut) is introduced; since the input loop would just determine if there is an action do to based of a table (or whatever) that is filled in during the initalization of the application, by calling the function `define_shortcut()`.
The help page i mentioned, would also be dinamically be filled in based on the info passed throughout the invocation of `define_shortcut()`.
Even in case of future implementation on a settings / features menu (like the current kindle reader, for the go-to, zoom etc..), I suppose having the needed data in a structured way would help the development.
What do you think about this approach? I may try to work on this

**Comment by dpavlin** [comment]
@traycold your approach seems similar to @hwhw but you propose to split key and modifier in two arguments? We could probably parse string for modifiers so they are quite similar.

My original suggestion included ev because I envisioned it being inside if/then/end constructs, so it was required to record exact event for later replay from menu. In your or @hwhw approach, we can generate events, so just ignore ev :-)

Feel free to hack at this problem, my time is somewhat limited lately. I would change order to

``` lua
define_shortcut(key, modifier, "do something nifty", function nifty()
 more code here
end )
```

This would allow documentation (help) to be on top of code to which it refers to.

**Comment by hwhw** [comment]
I had a short try today and noticed that this would imply some general changes to input handling as a whole. I'll happily hack on this. However, I think we should stabilize first and do a release, tag that version, and then move on with things like this. Maybe I'll start in a branch.

**Comment by houqp** [comment]
+1 for document on top of code.

**Comment by hwhw** [comment]
haha, I think our replys crossed :-) I vote for next.

**Comment by dpavlin** [comment]
+1 for next release (together with menu to select options without keyboard ;-)

**Comment by houqp** [comment]
> haha, I think our replys crossed :-) I vote for next.

Yes, I just noticed  it. You beat me this time :)

**Comment by houqp** [comment]
@traycold 

> What do you think about this approach? I may try to work on this

@hwhw 

> I'll happily hack on this.

You guys should talk over before the hacking. Otherwise we will have two branches. ;P

**Comment by traycold** [comment]
> > I'll happily hack on this.
> 
> You guys should talk over before the hacking. Otherwise we will have two branches. ;P

hi @hwhw, I'm also working on this, i'm committing a working proof-of version (still with half commands/shortcuts already encoded with the new way) on my repo, so feel free to have a look and in case i could make a pull request, when the branch is created on original repo. In any case, even we will never use it, I consider this useful (and funny, too!) for me as a lua-exercise (I just discovered lua through this application, and I like it very much! but it's indeed not so easy for me to get into it, since i came from Java world, so i like to write lua code).

**Comment by traycold** [comment]
Just some small comments on my code: it should be easy to replicate the same behaviour also on other user interface pages (like: filechooser), just modifying the input loop and defining the commands.
Moreover, it should be pretty easy to create a sort of on-line help (let's say, with shortcut H), that will list all the commands and the shortcuts. I also foresaw the possibility of "command-groups", like the keys 1,2..0 that could correspond to just one entry in the help page.
Last stage, would be to use these data to dinamically create a real menu to access at least the main function, like the native kindle reader.

**Comment by houqp** [comment]
looks good :) 

Finally, no more if elseif else end.

EDIT:
I think we need to come to an agreement on one coding styles. I have seen 3 or 4 styles in our code.

**Comment by dpavlin** [comment]
I'm one to blame for nonCamelCaps functions since I find underscores easier to read. I can adapt, I hope.

**Comment by houqp** [comment]
The [LuaStyleGuide](http://lua-users.org/wiki/LuaStyleGuide) did not specify a particular form for function name, but as a former Pythoner, I found underscores easier to read too.

I am also ok with camelCaps since it saves more line spaces ;P

**Comment by hwhw** [comment]
I'm fine with any style, but I'm easily distracted, too. I have no clear preferences and in my (half-)day job, I have to work within a jungle of styles (or the lack thereof). So: underscores are fine to me. But: what style will result in the least amount of needed fixes in the code? :-)

**Comment by houqp** [comment]
We are a little bit OT here. Not just functions' names but also variables'. I opened another issue for discussion on styles :)

**Comment by houqp** [comment]
Just noticed one thing, the command need a multiple key event to one function call API, so key events like "KEY_PGFWD" and "KEY_LPGFWD" can be mapped to the same action. Same thing also applies to "KEY_HOME" and "ALT+KEY_BACK" event. 

BTW, in previous design, HOME key is used to exist reader with one key press ;P

**Comment by houqp** [comment]
I think this issue can be closed?

**Comment by hwhw** [comment]
I agree. At least, for the moment. But I would prefer new tickets when other issues arise.
