### ISSUE TITLE
Rotating view should change zoom to fit mode too

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#572]
When I rotate screen for 90 degree, the default zoom mode is still fit page which is almost never wanted by the user.

So I suggest that when user rotate screen for 90 degree, the zoom mode should also change:
1. the default mode should be fit width. Nobody will rotate and read in fit page mode.
2. If user already used shift-X, the zoom mode should be fit content width.

When user rotate screen back to portrait mode, it should turn back to the previous zoom mode before rotating.

Of course user can still change the zoom mode if this is not what he want, but this design should fit most user's need.

**Comment by tigran123** [comment]
No, that is a bad idea, because: a) we should not make any assumptions about the aspect ratio of the page vs screen and b) software should implement mechanism but not policy, which should be left entirely up to the user. The least surprizing and most logical thing to do when rotating a page is to keep everything else intact. Making a simultaneous adjustment to the zoom mode is a policy, not a mechanism, so it should NOT be done without user's explicit request.

**Comment by dracodoc** [comment]
I don't agree with your points but there is little to argue here. I just submit another suggestion about this from another angle, and I believe that is much better than the solution I suggested here, so I'm closing this issue as it is not needed.
