### ISSUE TITLE
koptconfig dialog should exit after the user confirmed change.

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#576]
Normally user would call koptconfig to make a single change, not many. And having confirmed that change with fiveway select he would expect the configuration dialog to disappear. This is the normal behaviour in Amazon's framework's reader. But in KPV the user has to press Aa to get rid of the dialog. Can we change it to do the same as Amazon's "Aa" dialog, i.e. exit upon the user's confirmation of the setting?

**Comment by chrox** [comment]
No, not exiting the dialog after users confirmed change is a feature not a bug. The biggest difference between Koptreader and Amazon's reader is that parameter setting in Amazon's reader is predictable. You ask for less line space it will be less. And you ask for smaller font size it will do that. But the case in koptreader is totally different. Sometimes you confirm to select a larger font size but actually the font size in reflowed page doesn't change accordingly because the page size will exceed the limit. The mechanism of koptreader is heuristic and not predictable. I think we should reflect the internal mechanism to the user interface. So after being confirmed the dialog will still show and background page will be refreshed for the user to preview the change and try other parameters. Anyway if the user is satisfactory to the current page and wants to quit the dialog, he/she can do that by pressing the "Aa" or "F" definitely.

**Comment by kai771** [comment]
I agree with chrox on this issue. I can't check now, but doesn't pressing "Aa" when config dialog is open do confirm&close?

**Comment by tigran123** [comment]
@chrox In theory, your arguments are valid. In practice, however, they are not, for the following reasons:
1. The koptconfig dialog is quite big and in order to preview the changes (which, I agree, may often be not quite what the user expected due to heuristic nature of koptreader) the user has to press "Aa" to quit the dialog anyway. Otherwise the koptconfig dialog obscures most of the screen.
2. The chance of the user wishing to change more than one thing (without thoroughly previewing the intermediate result by quitting koptconfig dialog after a single change) are much lower than the chance of him wishing to change only one thing. Think of an average user (not an expert like yourself who actually wrote the thing and who knows koptreader's behaviour inside out) who is likely to just try changing font size. Precisely due to the heuristic nature of koptreader it is much more likely (and logical) for the user to try changing just one thing at a time rather than multiple parameters simultaneously.

@kai771 The second part of what you said solves the issue, thank you. I didn't realize that that is the case. I have just tried it and it works, i.e. pressing Aa actually confirms and closes the dialog, so the problem is solved and the issue can be closed. I originally thought that pressing Aa acts like Back i.e. cancels the changes.
