### ISSUE TITLE
add paperwhite support please.....

### ISSUE THREAD

**Issue by ahxxm** [koreader/kindlepdfviewer#632]
just sold my dxg, and planning to buy a paperwhite..

**Comment by tigran123** [comment]
Very bad idea to sell DXG in favour of paperwhite. You should buy Kindle 3 and DXG and forget about paperwhite, because these two models (Kindle 3 Keyboard and DXG) are far more superior technically to the primitive dumb-marketroid-driven paperwhite thing. The main advantages of Kindle 3 and DXG compared to paperwhite are:
1. No touch screen support meaning [slightly] better quality output on the eInk screen.
2. No light diffusing layer meaning MUCH BETTER quality output on the eInk screen.
3. Audio support (inc microphone)
4. Better battery
5. Twice as much local storage (4GB vs 2GB)
6. Fully jailbroken with KPV supported and polished almost to perfection.

**Comment by ahxxm** [comment]
LOL
i'm (gonna) trying to port the KPV to paperwhite
thanks anyway

**Comment by chrox** [comment]
@ahxxm That will be great. @houqp is already doing the porting thing with a bland new UI framework. It's much easier to start there. You can checkout the new_ui_code branch with this command `git checkout new_ui_code` after you clone hwhw's KPV repo.

**Comment by tigran123** [comment]
@ahxxm You are welcome. I was going to mention the `new_ui_code` branch but I see @chrox already did that. Anyway, you can compile it in the emulator mode to run under x86 or x86_64 architectures (under Linux of course) to see how much of it is working already.

**Comment by neharon** [comment]
Add my voice to paperwhite support please.
Thanks.

**Comment by houqp** [comment]
hi all, PW is in progress, 70% done I think: https://github.com/hwhw/kindlepdfviewer/tree/new_ui_code

I would say reflow and epub is actually usable now, but other features are still under development.

I am working on the screen rotate feature. It's almost done and I will clean up the code in following days.

**Comment by neharon** [comment]
wait&hope :^)

**Comment by houqp** [comment]
closing for now, PW user please use KOReader
