### ISSUE TITLE
"mp3 support"

### ISSUE THREAD

**Issue by mayabtlaloc** [koreader/kindlepdfviewer#635]
"mp3 support" is this very difficult? is to listen a soft music while reading

**Comment by tigran123** [comment]
The built-in Amazon's mp3 player works fine --- just copy your mp3 files to "music" directory and press Alt-Space key before starting up KPV.

**Comment by mayabtlaloc** [comment]
thank you. but only plays one song and stops, there is not a continuous player . I do not know why it does that.

**Comment by tigran123** [comment]
Is that so? Ok, this is something we can look into _after_ the stable v2012.11 release which is imminent.

**Comment by tigran123** [comment]
I have just replied to your post on the-ebook.org, explaining that if you control mplayer outside of KPV (instead of using Amazon's built-in mp3 player) then it works fine, i.e. plays all files in music directory even if you start KPV in "kill Amazon framework" mode via Shift-P-K. And works in Shift-P-D mode too. So, download mplayer for Kindle from here and enjoy:

http://www.mobileread.com/forums/showthread.php?t=119851

**Comment by mayabtlaloc** [comment]
tigran123 thanks, it works!
