### ISSUE TITLE
Problem with nightly builds of master?

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#645]
I would like to know if there is a problem with the nightly builds of master. There are only two files there and their date stamps are separates by several days. The main advantage of having nightly builds is so that we have a wide selection of "check-points" which we can test very quickly to narrow down where some bug was introduced. So, that means having at least 60-70 previous builds.

**Comment by chrox** [comment]
No. Because nightly builds will overwrite existing builds with the same SHA string and only keep builds of the recent week. So it means that only two new commits or tags are on the tip of master tree in this week. I can change the time span to the recent month so that there will be more install/test options.

**Comment by tigran123** [comment]
@chrox That is a very good idea (overwriting identical SHA builds) --- I am glad you did it that way.

As for one week --- yes, I think it would be nicer if you change it to one month at least. Sometimes bugs are not noticed until at least a few weeks have passed since it was introduced (especially memory corruptions, like the one we had with djvulibre some time ago).

**Comment by chrox** [comment]
OK. I have changed the expiration of builds to one month as in https://gist.github.com/4002028

**Comment by tigran123** [comment]
Thank you very much, closing the issue.
