### ISSUE TITLE
PDF files rendered as blank page when missing DroidSansFallback.ttf font

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#660]
So in one of our previous issue #542, we decided to kick `DroidSansFallback.ttf` out of KPV distribution. It turns out that mupdf don't buy this and one of my test book is rendered in blank pages ;p

file link:
https://www.dropbox.com/sh/1w3ow4v4t47ioqf/A0j2Etwdso/%E6%95%B0%E5%AD%A6%EF%BC%9A%E7%A1%AE%E5%AE%9A%E6%80%A7%E7%9A%84%E4%B8%A7%E5%A4%B1.pdf

(before you test on emulator, remember to rename DroidSansFallback.ttf in fonts/droid dir)

**Comment by tigran123** [comment]
Confirmed. Ok, let's restore DroidSansFallback.ttf into our distribution.

**Comment by hwhw** [comment]
I guess that's my fault, I didn't reflect the change to the ...Full font in
the muPDF patch. The muPDF patch essentially makes muPDF use files instead
of compiling the fonts into the library (which we don't want since the
fonts are used in other places, too). But going back is fine for me, too -
I still didn't get to actually check what the ...Full fonts adds.

**Comment by tigran123** [comment]
Going back is safer because we don't know exactly what the "Full" version adds. Maybe when/if we find that out, we'll make a decision to switch to it. Ok? Shall I do a PR (I know @houqp is busy with paperwhite support)?

**Comment by hwhw** [comment]
Of course this is OK. Maybe we should have waited for an issue that could
be fixed by going to the "Full" version before switching in the first
place. So just go on! I just wanted to add a bit of info where the problem
stems from.

**Comment by houqp** [comment]
patch merged, thanks @tigran123 and @hwhw  :)
