### ISSUE TITLE
page view mode sometimes jump multiple pages on page turn.

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#679]
I just found out this bug. So far I cannot find a good way to reproduce it, but when you open a document, and keep doing page turn, you will sometimes see the page number on header is incremented by 2 instead of 1.

This is because we are still using position inside document for navigation in page view mode, which is wrong. In page view mode, we should use page number instead.

I fixed this bug in new ui code branch:
https://github.com/houqp/kindlepdfviewer/commit/93abd2fee73107adbee9fc09c27b1945ae422887

Haven't got time to fix it in master branch yet, because I am going out for 3 weeks traveling tomorrow and still haven't pack my baggage ;p

So probably I won't be able to do any serious coding for the next three weeks. Wish every one has a wonderful holiday and happy hacking :)

PS: If this bug is still not fixed after I get back to my laptop weeks later, I will give it a try. Hopefully, this won't be the case ;p

**Comment by mayabtlaloc** [comment]
not yet come back from vacation houqp, I can not read well with this bug!!

**Comment by tigran123** [comment]
@mayabtlaloc I thought it was just a cosmetic bug whereby the page number (which is meaningless for ebooks anyway) is sometimes shown incorrectly, but the actual text is rendered correctly, i.e. the text on the next "page" follows precisely the text on the current "page". Is this not the case? I.e. is the reader actually showing the WRONG text sometimes? If so, then, yes, it would be a real (not cosmetic) bug.

**Comment by kai771** [comment]
@mayabtlaloc In the meantime, you can try Librerator, my fork of KPV. This bug is corrected there. You can get it [here](http://www.mobileread.com/forums/showthread.php?t=198742).

@tigran123 it's not a "cosmetic" bug.

**Comment by mayabtlaloc** [comment]
tigran123 It is not really a cosmetic error. the reader is also showing wrong text. I will try "Librerator" , Thanks kai771.

**Comment by tigran123** [comment]
@mayabtlaloc Ah, I see, I misunderstood the description. I thought it was only showing the wrong page number in the top right corner. But yes, if it is actually showing the wrong text then it is a critical bug that ought to be fixed.

**Comment by houqp** [comment]
I will be back the day after tomorrow :)

ATM, I am guiding a new developer through the fixing so he can get familiar with the code base and we can get more developers ;p

For now, I would also recommend you use Liberator since it is fixed there.

**Comment by mayabtlaloc** [comment]
I've installed liberator (It has very good modifications) and effectively this bug has been fixed. thanks for the efforts of all developers, and also welcome the new developer!

**Comment by kai771** [comment]
@mayabtlaloc I'm glad you like it :). And btw, it's Lib **re** rator, and not Lib **er** ator. :). It's on purpose ;)

**Comment by mayabtlaloc** [comment]
sorry, kai771, you're right, Librerator is very good,  abusing a little, it would not be possible to include option to modify margins in crereader, and enable pdf reflow hyphenation?.  I would like to know your opinion about it

**Comment by kai771** [comment]
@mayabtlaloc Nothing to be sorry about :). Margins in crereader might be quite feasible, but I'm not really familiar with crengine api. As I stated a number of times before, I'm not really a developer. I'm just a noob. Some changes to the user interface is the best I can do. If someone finds the needed functions and documents them, I might be able to add it to Librerator. Otherwise, there's nothing I can do.

As for pdf and djvu reflow, it's chrox' area of expertise, so you should ask him for a definite answer. But, as far as I understand it, it won't be feasible. Reflow is done with bitmaps. Meaning, the reflow reader is not aware what are the words that it's reflowing. It cuts pieces of already rendered bitmap and rearanges them. It uses gaps within the lines to find where it's appropriate to cut (that is, it trys to cut on word boundaries). Therefore, I don't think it would be feasible to make it do hyphenation (well, at least not easily. It would require some serious work, including OCR of the text). Also, you shouldn't forget that reflow should be useful for languages other than English, too (like Chinese for example). 

The solution would be to make another reflow reader, which would get actual text from pdf files. But, this kind of reflow reader would not work on scaned pdfs (and there are meany of those), and imno, wouldn't be nowhere near the quality of the current implementation. Not to mention that someone would have to write it from scratch, which is a time consuming task. It would be only useful for reading novels or similar types of documents with not demanding formating. Given the amount of work needed, limited amount of usefulness and presence of already working solution that works with much broader array of documents, I doubt anyone would bother with writing one. Just my noob opinion though :).

**Comment by mayabtlaloc** [comment]
Thanks for your response, I think the developers need people like you too, I appreciate your work.

**Comment by houqp** [comment]
Yes, @kai771 is still with us ;p 

We still share new fixes and features between kpv and libreator.

OK, fixes is merged to master branch now by #692, so this issue should be closed.
