### ISSUE TITLE
unable to return to the native system :(

### ISSUE THREAD

**Issue by th0mass** [koreader/kindlepdfviewer#814]
the problems stated on #749 still valid :(
home button works but returns to file manager of KPV (not to the original system)
file manager menu still not appear except from the just after the launch of the app.

using 5.3.2.1 -KUAL- -20130320

**Comment by houqp** [comment]
OK, let me test it again tonight ;p

So KT user can get around with home key right?

**Comment by th0mass** [comment]
unfortunately not. home button opens the "KPV  file manager " not the native one. only way is the hard reset. (like the home button in the reader menu)

**Comment by houqp** [comment]
Um... Could you help me this it by replacing the reader.lua(under KPV root dir) with following content?
https://raw.github.com/houqp/kindlepdfviewer/7f32b427ea27e360841d7d83a81795c862f6ac3f/reader.lua

It exit the reader, instead of invoking the menu on home key press.

What I have found out so far is after exit from a document and wait an unreasonably long time, the menu start to working again. So I suspect it might related to GC in lua runtime.

Will look into further in following days

**Comment by th0mass** [comment]
tried after resetting kindle to factory defaults in case some changes in Kindle cause this problem.
now it exits in both reader.lua but the existing one exits but not replaces the  chrome bar  
the one you give the link above exits without any problem so far. ( but I guess we need some feedback from a different Kindle Touch ) 

edit:  both the home button stop responding and the upper menu in the file manager doesn't appear when I get around the menu back and forth 

I added the existing exit function as a new "quit" tab like home button on readermenu to have this option in case of fails of the original one. 
![2013-03-23 16 17 52](https://f.cloud.github.com/assets/1252713/293966/b91ecabc-93c4-11e2-89b2-45789879bad4.jpg)

**Comment by houqp** [comment]
Thanks for your report and hack :)

I am closing this issue for now since we should move the discussion to the new repo ;p

https://github.com/koreader/koreader/issues/15
