### ISSUE TITLE
Place for storing highlights?

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#89]
Just notice that Amazon store the PDF's annotation and highlights in a seperate PDR file. Should we follow this approach? Currently, for djvu, we store highlight in book's setting files which may grow large and unmanageable for users if there are too many highlights.

**Comment by dpavlin** [comment]
I like the fact that we store highlights together with other data in lua file. This could allow someone to write tool which turns it back to pdf annotations on laptop for example :-)

I had a look at http://code.google.com/p/kindle-annotations/wiki/PDRFileFormat and even wrote some code at https://github.com/dpavlin/k3libre/blob/master/pdr-dump.pl and it seems to me that PDR compatibility would be nice, at least for read-only support since we don't understand enough of format to implement it fully.

**Comment by houqp** [comment]
I love storing data in Lua too :)  Actually, I mean storing highlight data in another Lua file ;P

Yes, nice to bring PDR read support. Hope the highlight support in MuPDF can be implemented in the near future.

**Comment by hwhw** [comment]
Well, having a total of three files for a single document is a bit verbose, I think. But then - I would not really care.

Highlighting for muPDF is something I would like to tackle as soon as I'm in front of my development PC again.

**Comment by houqp** [comment]
> Well, having a total of three files for a single document is a bit verbose, I think. But then - I would not really care.

Agree, I will just close it. Let's split it when it become a bottleneck in the future. After all, I am just imaging it ;P
